import {Button,Checkbox,FormControlLabel,TextField} from '@mui/material';
import ReportLookup from './ReportLookup.jsx';
const options={payment_status:[['all','All statuses'],['paid','Paid'],['partial','Partial'],['unpaid','Unpaid'],['credit','Credit / refund due']],stock_status:[['all','All stock'],['in','In stock'],['low','Low stock'],['out','Out of stock']],active:[['true','Active'],['false','Inactive'],['all','All products']],movement_type:['all','PURCHASE','SALE','ADJUSTMENT_IN','ADJUSTMENT_OUT','SALE_RETURN','PURCHASE_RETURN','OPENING_STOCK'].map((value)=>[value,value==='all'?'All movements':value.replaceAll('_',' ')])};
const labels={payment_status:'Payment status',stock_status:'Stock status',active:'Product status',movement_type:'Movement type'};
export default function ReportFilters({config,draft,setDraft,onApply,onReset,busy}) {
  const change=(key,value)=>setDraft((d)=>({...d,[key]:value,...(key==='customer_id'&&value?{walk_in:false}:{}),...(key==='walk_in'&&value?{customer_id:null}:{})}));
  return <form className="flex flex-wrap items-start gap-3" onSubmit={(e)=>{e.preventDefault();onApply();}}>
    {config.dated&&<TextField select size="small" label="Period" name="report-period" value={draft.period} onChange={(e)=>change('period',e.target.value)} slotProps={{select:{native:true}}}>{[['today','Today'],['week','Last 7 days'],['month','This month'],['year','This year'],['custom','Custom range']].map(([value,label])=><option key={value} value={value}>{label}</option>)}</TextField>}
    {config.dated&&draft.period==='custom'&&['from_date','to_date'].map((key)=><TextField key={key} required size="small" type="date" label={key==='from_date'?'From date':'To date'} name={`report-${key}`} value={draft[key]||''} onChange={(e)=>change(key,e.target.value)} slotProps={{inputLabel:{shrink:true}}}/>)}
    {config.fields.map((field)=>field.endsWith('_id')?<ReportLookup key={field} field={field} value={draft[field]} onChange={(value)=>change(field,value)}/>:field==='walk_in'?<FormControlLabel key={field} control={<Checkbox name="report-walk_in" checked={draft.walk_in} onChange={(e)=>change(field,e.target.checked)}/>} label="Walk-in only"/>:options[field]?<TextField key={field} select size="small" label={labels[field]} name={`report-${field}`} value={draft[field]} onChange={(e)=>change(field,e.target.value)} slotProps={{select:{native:true}}}>{options[field].map(([value,label])=><option key={value} value={value}>{label}</option>)}</TextField>:<TextField key={field} size="small" label={field==='search'?(config.method==='getSales'||config.method==='getPurchases'?'Invoice search':'Search'):'Payment method'} name={`report-${field}`} value={draft[field]} onChange={(e)=>change(field,e.target.value)} helperText={field==='payment_method'?'Use all, Cash, Bank transfer, Cheque or an exact recorded method.':undefined} slotProps={{htmlInput:{maxLength:field==='search'?200:80}}}/>)}
    <Button type="submit" variant="contained" disabled={busy}>Apply filters</Button><Button onClick={onReset} disabled={busy}>Reset filters</Button>
  </form>;
}
