import {useEffect,useState} from 'react';
import {Alert,Button,Paper,Tab,Tabs,Table,TableBody,TableCell,TableContainer,TableHead,TableRow,TextField} from '@mui/material';
import {catalogRequest,formatPrice} from '../utils/catalog.js';
import ReturnDialog from '../components/returns/ReturnDialog.jsx';
import ReturnDetails from '../components/returns/ReturnDetails.jsx';
function Workspace({kind}){
  const sale=kind==='sale',resource=sale?'saleReturns':'purchaseReturns';
  const [view,setView]=useState('invoices'),[search,setSearch]=useState(''),[query,setQuery]=useState(''),[page,setPage]=useState(0),[revision,setRevision]=useState(0);
  const [state,setState]=useState({loading:true,rows:[],error:''}),[invoice,setInvoice]=useState(null),[details,setDetails]=useState(null),[notice,setNotice]=useState('');
  useEffect(()=>{let live=true;setState({loading:true,rows:[],error:''});catalogRequest(()=>view==='history'?window.api[resource].list({search:query,limit:25,offset:page*25}):window.api[sale?'sales':'purchases'].list({search:query,limit:25,offset:page*25})).then((data)=>{if(live)setState({loading:false,rows:Array.isArray(data)?data:data.rows,error:''});}).catch((e)=>{if(live)setState({loading:false,rows:[],error:e.message});});return()=>{live=false;};},[view,resource,sale,query,page,revision]);
  async function showDetails(id){setNotice('Loading return details...');try{setDetails(await catalogRequest(()=>window.api[resource].getById(id)));setNotice('');}catch(e){setNotice(e.message);}}
  return <><Tabs value={view} onChange={(_,v)=>{setView(v);setPage(0);}} aria-label="Return view"><Tab value="invoices" label="Select invoice"/><Tab value="history" label="Return history"/></Tabs>
    <Paper variant="outlined" sx={{p:2,my:2}}><form className="flex flex-wrap gap-3" onSubmit={(e)=>{e.preventDefault();setQuery(search);setPage(0);setRevision((r)=>r+1);}}><TextField size="small" label="Invoice / account search" name="return-search" value={search} onChange={(e)=>setSearch(e.target.value)}/><Button type="submit" disabled={state.loading}>Search</Button><Button disabled={state.loading} onClick={()=>setRevision((r)=>r+1)}>Refresh</Button></form></Paper>
    {notice&&<Alert sx={{mb:2}}>{notice}</Alert>}
    {state.loading?<p role="status">Loading returns...</p>:state.error?<Alert severity="error" action={<Button onClick={()=>setRevision((r)=>r+1)}>Retry</Button>}>{state.error}</Alert>:<Paper variant="outlined" sx={{overflow:'hidden'}} data-returns-ready>
      {!state.rows.length?<p className="p-6">{view==='history'?'No returns found.':'No invoices found.'}</p>:<TableContainer><Table size="small" aria-label={view==='history'?'Return history':'Return invoices'}><TableHead><TableRow>{(view==='history'?['Reference','Invoice','Account','Date','Items','Return value','Notes','Action']:['Invoice','Account','Original total','Returned value','Effective total','Credit / refund due','Action']).map((s)=><TableCell key={s}>{s}</TableCell>)}</TableRow></TableHead><TableBody>{state.rows.map((row)=><TableRow key={row.id} data-return-row>
        {view==='history'?<><TableCell>{row.reference}</TableCell><TableCell>{row.invoice_number}</TableCell><TableCell>{row.contact_name||'Walk-in'}</TableCell><TableCell>{row.returned_at}</TableCell><TableCell>{row.item_count}</TableCell><TableCell>{formatPrice(row.total)}</TableCell><TableCell sx={{maxWidth:240,overflowWrap:'anywhere'}}>{row.notes}</TableCell><TableCell><Button onClick={()=>showDetails(row.id)}>Details</Button></TableCell></>:<><TableCell>{row.invoice_number}</TableCell><TableCell>{row.customer_name||row.supplier_name||'Walk-in'}</TableCell>{[row.total,row.returned_value,row.effective_total,row.credit_due].map((n,i)=><TableCell key={i}>{formatPrice(n)}</TableCell>)}<TableCell><Button aria-label={`Return ${row.invoice_number}`} onClick={()=>setInvoice(row.id)}>Return items</Button></TableCell></>}
      </TableRow>)}</TableBody></Table></TableContainer>}
      <div className="flex items-center justify-end gap-3 p-3"><Button disabled={!page} onClick={()=>setPage((p)=>p-1)}>Previous</Button><span>Page {page+1}</span><Button disabled={state.rows.length<25} onClick={()=>setPage((p)=>p+1)}>Next</Button></div>
    </Paper>}
    {invoice!==null&&<ReturnDialog kind={kind} invoiceId={invoice} onClose={()=>setInvoice(null)} onSaved={(result)=>{setInvoice(null);setNotice(`Return ${result.document.reference} recorded. Credit / refund due: ${formatPrice(result.invoice.credit_due)}`);setView('history');setQuery('');setSearch('');setPage(0);setRevision((r)=>r+1);}}/>}
    {details&&<ReturnDetails document={details} onClose={()=>setDetails(null)}/>}
  </>;
}
export default function ReturnsPage(){const [kind,setKind]=useState('sale');return <section className="mx-auto min-w-0 max-w-screen-2xl"><h1 id="page-title" className="text-3xl font-semibold">Returns</h1><p className="mt-2 mb-4 text-sm text-slate-500">Return items against original invoices and review immutable return history.</p><Tabs value={kind} onChange={(_,v)=>setKind(v)} aria-label="Return type"><Tab value="sale" label="Sale Returns"/><Tab value="purchase" label="Purchase Returns"/></Tabs><Workspace key={kind} kind={kind}/></section>;}
