import {Button,Table,TableBody,TableCell,TableContainer,TableHead,TableRow} from '@mui/material';
import {formatPrice} from '../../utils/catalog.js';
const date=(value)=>value.length===10?value:new Date(value).toLocaleString('en-PK');
export default function PaymentTable({data,history,page,onPage,onPay}) {
  const headings=history?['Payment date','Account','Invoice','Method','Amount','Notes / Reference']:['Invoice','Account','Invoice date','Original total','Returned value','Effective total','Paid so far','Outstanding','Status','Action'];
  return <>
    {!data.rows.length?<p role="status" className="p-12 text-center text-slate-500">{history?'No payments found.':'No open invoices found.'}</p>:<TableContainer tabIndex={0} aria-label="Payment table, scroll for more columns"><Table size="small" aria-label={history?'Payment history':'Open invoices'} sx={{minWidth:850,'& thead th':{bgcolor:'#f8fafc',fontWeight:600},'& td':{py:1.5}}}><TableHead><TableRow>{headings.map((heading)=><TableCell key={heading} align={['Amount','Original total','Returned value','Effective total','Paid so far','Outstanding'].includes(heading)?'right':'left'}>{heading}</TableCell>)}</TableRow></TableHead><TableBody>{data.rows.map((row)=><TableRow key={row.id} data-payment-row={row.id}>
      {history?<><TableCell sx={{whiteSpace:'nowrap'}}>{date(row.paid_at)}</TableCell><TableCell>{row.contact_name}</TableCell><TableCell>{row.invoice_number}</TableCell><TableCell>{row.payment_method}</TableCell><TableCell align="right" sx={{whiteSpace:'nowrap'}}>{formatPrice(row.amount)}</TableCell><TableCell sx={{maxWidth:300,overflowWrap:'anywhere',whiteSpace:'pre-wrap'}}>{row.notes||'—'}{row.reference&&<p>{row.reference}</p>}</TableCell></>:<><TableCell>{row.invoice_number}</TableCell><TableCell>{row.contact_name}{row.active===0?' (inactive)':''}</TableCell><TableCell sx={{whiteSpace:'nowrap'}}>{date(row.invoice_date)}</TableCell>{['total','returned_value','effective_total','paid_amount','balance'].map((key)=><TableCell key={key} align="right" sx={{whiteSpace:'nowrap'}}>{formatPrice(row[key])}</TableCell>)}<TableCell>{row.payment_status.toUpperCase()}</TableCell><TableCell><Button size="small" aria-label={`Pay ${row.invoice_number}`} onClick={()=>onPay(row.id)}>Record payment</Button></TableCell></>}
    </TableRow>)}</TableBody></Table></TableContainer>}
    <div className="flex flex-wrap items-center justify-between gap-2 p-3"><span className="text-sm text-slate-500" data-payment-page>Page {page+1} of {Math.max(1,Math.ceil(data.totalRows/25))} · {data.totalRows} records</span><div><Button disabled={!page} onClick={()=>onPage(page-1)}>Previous</Button><Button disabled={(page+1)*25>=data.totalRows} onClick={()=>onPage(page+1)}>Next</Button></div></div>
  </>;
}
